# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'COVID19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID19
  pod 'Alamofire'
  pod 'Charts'

end
